### ISSUE TITLE
[1.19.2] Ticking Entity crash with Silent Compat.

### ISSUE THREAD

**Issue by Gbergz** [dragoni7/Silent-Compat#14]
Title ^

Ticking Entity server crash randomly. Not sure the exact cause.

Forge: 43.2.14
MC: 1.19.2
Silent Compat: 2-1.3
Silent Gear: 3.2.6
Silent Lib: 7.0.3

Crash-Report: https://gist.githubusercontent.com/Gbergz/3304d5b9cbc0dafd6348be6bdc218313/raw/f61cf8abcd8898127788658be5cd8052d9af3c1d/gistfile1.txt

**Comment by dragoni7** [comment]
Hi, there seems to be an issue with the code for ItemDropTrait. For now any tools with an item drop trait will likely cause a crash.
I'll get a fix out for it asap!

**Comment by Gbergz** [comment]
Thanks! :)
