### ISSUE TITLE
Contributing custom textures for Fiery material

### ISSUE THREAD

**Issue by farinc** [dragoni7/Silent-Compat#16]
So I have been sitting under a rock for a while and I have been working on my own addon for Silent Gear and Twilight Forest ([link](https://github.com/farinc/twilightgear)). I didn't realize this addon also add twilight forest materials, so I would love to contribute to what is already around and possibly abandon by tiny addon. 

Something I did notice is that the fiery material here only gets a overlay color like most materials. I recently made custom animated textures to get a similar look-and-feel to the original twilight forest (which I love the aesthetic).

The only difference seems to be that I choose to have fiery blood/tears as a coating instead of using the fiery ingot directly, so for that reason my textures at this point only cover the "main" of tools, with the exception of the armor model texture (and shield which I am not sure if this possible...). Although the rest is relatively easy to do (fragments, parts, etc)

If your interested once I am done I can do a pull request for those custom textures!

**Comment by dragoni7** [comment]
I would not mind a pull request, your implementation makes more sense. I would be happy to give credit for the contribution however you want.
Don't feel obliged to do a pull request either, publishing your own standalone mod is also fine!
Feel free to dm request me on discord if needed, sometimes I forget to check the server
