### ISSUE TITLE
So this happened

### ISSUE THREAD

**Issue by Kuggle01** [dragoni7/Silent-Compat#2]
https://bytebin.lucko.me/yWpmY9ukIZ The game just crashed when I punched a baby skeleton from Born in choas. I have no idea how or why this happened???

**Comment by P3rf3ctXZer0** [comment]
Yeah that is what I was going to report too.

**Comment by lamoyrl90** [comment]
Yeah, latest SG seems to have changed a couple methods that were used in this mod? DataResource.trait(ResourceLocation) doesn't seem to be correct anymore for some reason. I just looked through SG's code and it looks like that DataResource class was deprecated in favor of the one in the API package. Not sure why it doesn't work though, looks like the deprecated one just inherits the API class, which has the method you were using. Probably something on SG's end, incorrectly extending the API class to account for older code but accidentally breaking it instead.

Either way, it's probably best to switch this mod's code to use the API.

**Comment by P3rf3ctXZer0** [comment]
Also a lot of it has to do with born in chaos too. During my testing it seems there are some fairly large render and thread no nos. I opted to remove BiC until further notice.

**Comment by Maddremor** [comment]
It has been reported and attempts has been made to alleviate it on the SG side. 
[Issue](https://github.com/SilentChaos512/Silent-Gear/issues/569)
[First commit](https://github.com/SilentChaos512/Silent-Gear/commit/fa527b3ab75f60502f85658ab420402945f2534b)
[Second commit](https://github.com/SilentChaos512/Silent-Gear/commit/4176dcf0bd479e8256b86ed9b8b13c035522aa32)
[Third commit](https://github.com/SilentChaos512/Silent-Gear/commit/4b4d87e43779fbb9841b32a820739fbd8c4f6908)

**Comment by dragoni7** [comment]
Should be fixed in latest versions
