### ISSUE TITLE
Config for changing attributes and spawn-rate

### ISSUE THREAD

**Issue by Zkaface** [dragoni7/Silent-Compat#8]
Could you implement a config file so that we are able to change the frequency of generation of the native mod ores and the attributes of materials? When using the mod in my servers, it won't fit in very balanced, so i would nerf the attributes a little bit.

Thanks in advance, wheter it's possible or not.

**Comment by dragoni7** [comment]
Hello, the generation can be tweaked with a data pack. Any data pack tutorial should work for understanding how to do that.
The data files for the mod can be located here: 
https://github.com/dragoni7/Silent-Compat/tree/main/src/main/resources/data/silentcompat

The same would apply to editing material attributes:
https://github.com/SilentChaos512/Silent-Gear/wiki
