### ISSUE TITLE
Mekanism materials

### ISSUE THREAD

**Issue by JWTHDYTWA** [dragoni7/Silent-Compat#9]
For now Mekanism materials stats are ABSOLUTELY INAPPROPRIATE.
To understand, Antimatter is one of the most difficult items to get, independant on which modpack are you playing. You need ~10000 uranium ingots, many thousands of sulfur+fluorite, complex machine sequence and tons of time to obtain 1 piece of antimatter. 1.25x damage multiplier for it is ridiculous.

The same thing with Polonium, however it's much cheaper.

**Comment by dragoni7** [comment]
I can revisit the stats for these, though it is also possible to edit the stats yourself for any material you please. This can be done with datapacks as SilentGear allows.
See: https://github.com/SilentChaos512/Silent-Gear/wiki
